### ISSUE TITLE
Bitcoinrpc has an error with running of eloipool

### ISSUE THREAD

**Issue by jeong760** [jgarzik/python-bitcoinrpc#66]
Dears, 

Whenever I running a Eloipool I saw following error on log file.
so I think that error related with bitcoinrpc.

2016-04-30 04:21:11,338 BitcoinRPC      DEBUG   -1-> getblocktemplate [{"capabilities": ["coinbasevalue", "coinbase/append$
2016-04-30 04:21:11,365 BitcoinRPC      DEBUG   <-1- {"coinbasevalue": 2527191892, "capabilities": ["proposal"], "sizelimi$
2016-04-30 04:21:11,371 merkleMaker     INFO    New block: 000000000000000001893e44352e7cd4c7e33d8249068bee3d9ab5f47ae375b$
2016-04-30 04:21:11,372 JSONRPCServer   INFO    Waiting 15 seconds to longpoll
2016-04-30 04:21:11,381 BitcoinRPC      DEBUG   -2-> getblocktemplate [{"mode": "proposal", "data": "04000000b575e37af4b59$
2016-04-30 04:21:11,394 BitcoinRPC      DEBUG   <-2- null
2016-04-30 04:21:11,395 BitcoinRPC      DEBUG   -3-> getblocktemplate [{"capabilities": ["coinbasevalue", "coinbase/append$
2016-04-30 04:21:11,447 BitcoinRPC      DEBUG   <-3- {"coinbasevalue": 2527191892, "capabilities": ["proposal"], "sizelimi$
2016-04-30 04:21:11,463 BitcoinRPC      DEBUG   -4-> getblocktemplate [{"mode": "proposal", "data": "04000000b575e37af4b59$
2016-04-30 04:21:11,476 BitcoinRPC      DEBUG   <-4- null
2016-04-30 04:21:11,476 merkleMaker     CRITICAL        Traceback (most recent call last):
  File "/eloipoolsrv/merklemaker.py", line 704, in run
    self.merkleMaker_I()
  File "/eloipoolsrv/merklemaker.py", line 694, in merkleMaker_I
    self.merkleMaker_II()
  File "/eloipoolsrv/merklemaker.py", line 660, in merkleMaker_II
    return self._updateMerkleTree()
  File "/eloipoolsrv/merklemaker.py", line 560, in _updateMerkleTree
    self._updateMerkleTree_I()
  File "/eloipoolsrv/merklemaker.py", line 546, in _updateMerkleTree_I
    raise RuntimeError('Failed to create usable template')
RuntimeError: Failed to create usable template

Regards,
John Ahn

**Comment by jgarzik** [comment]
not related to this project
